# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/samta',
                'doc_host': 'https://karnsaurabhkumar.github.io',
                'git_url': 'https://github.com/karnsaurabhkumar/samta',
                'lib_path': 'samta'},
  'syms': {'samta.core': {'samta.core.foo': ('core.html#foo', 'samta/core.py')}}}
